export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_USERS = 'GET_USERS';
export const GET_EXERCISE_BY_ID = 'GET_EXERCISE_BY_ID';
export const FILTER_BY_MUSCLE = 'FILTER_BY_MUSCLE'
export const ORDER_BY_NAME = 'ORDER_BY_NAME'
