//EXERCISES
export const GET_EXERCISES = "GET_EXERCISES";
export const GET_EXERCISE_BY_ID = "GET_EXERCISE_BY_ID";
export const FILTER_BY_MUSCLE = "FILTER_BY_MUSCLE";
export const GET_NAME_EXERCISES = "GET_NAME_EXERCISES";
export const ORDER_BY_NAME = "ORDER_BY_NAME";

//PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ORDER_PRODUCTS = "ORDER_PRODUCTS";
export const POST_PRODUCT_CREATE = "POST_PRODUCT_CREATE";
export const GET_NAME_PRODUCTS = "GET_NAME_PRODUCTS";

//USERS
export const GET_USERS = "GET_USERS";
export const POST_REGISTER = "POST_REGISTER";

// CARRITO
//export const ADD_PRODUCTS = 'ADD_PRODUCTS';
//export const ADD_TO_CART = 'ADD_TO_CART';
//export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART';
//export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
//export const CLEAR_CART = 'CLEAR_CART';
